# -*- coding: utf-8 -*-
"""run_mimic_classifier_oldgate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KRFW6_RG2t59Ogw9Gxp-1qfjz3_YlUTm
"""

import os
import gc
import math
import argparse
from pathlib import Path

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from sklearn.metrics import (
    roc_auc_score,
    average_precision_score,
    accuracy_score,
    f1_score,
)

# --------------------------------------------------
# Paths
# --------------------------------------------------
REPO_ROOT = Path("/content/drive/MyDrive/IMM-TSF")
DATA_ROOT = REPO_ROOT / "data" / "MIMIC"
PROCESSED_DIR = DATA_ROOT / "processed"
LABEL_DIR = DATA_ROOT / "labels"

# --------------------------------------------------
# Helpers
# --------------------------------------------------
def set_seed(seed=1):
    import random
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

def safe_auc(y_true, y_prob):
    y_true = np.asarray(y_true)
    y_prob = np.asarray(y_prob)
    if len(np.unique(y_true)) < 2:
        return np.nan
    return roc_auc_score(y_true, y_prob)

def safe_auprc(y_true, y_prob):
    y_true = np.asarray(y_true)
    y_prob = np.asarray(y_prob)
    if len(np.unique(y_true)) < 2:
        return np.nan
    return average_precision_score(y_true, y_prob)

# --------------------------------------------------
# Label builders
# --------------------------------------------------
def build_mortality_labels(mimic_root: str):
    hosp_dir = Path(mimic_root) / "hosp"
    adm = pd.read_csv(hosp_dir / "admissions.csv.gz", low_memory=False)

    adm["hadm_id"] = pd.to_numeric(adm["hadm_id"], errors="coerce").astype("Int64")

    if "hospital_expire_flag" in adm.columns:
        adm["label"] = pd.to_numeric(adm["hospital_expire_flag"], errors="coerce").fillna(0).astype(int)
    else:
        adm["deathtime"] = pd.to_datetime(adm.get("deathtime"), errors="coerce")
        adm["label"] = adm["deathtime"].notna().astype(int)

    out = adm[["hadm_id", "label"]].dropna().copy()
    out["hadm_id"] = out["hadm_id"].astype(int)
    return out

def build_icu_readmit_labels(mimic_root: str):
    icu_dir = Path(mimic_root) / "icu"
    icu = pd.read_csv(icu_dir / "icustays.csv.gz", low_memory=False)

    icu["subject_id"] = pd.to_numeric(icu["subject_id"], errors="coerce")
    icu["hadm_id"] = pd.to_numeric(icu["hadm_id"], errors="coerce")
    icu["intime"] = pd.to_datetime(icu["intime"], errors="coerce")
    icu["outtime"] = pd.to_datetime(icu["outtime"], errors="coerce")

    icu = icu.dropna(subset=["subject_id", "hadm_id", "intime", "outtime"]).copy()
    icu = icu.sort_values(["subject_id", "intime"]).copy()

    icu["next_intime"] = icu.groupby("subject_id")["intime"].shift(-1)
    icu["days_to_next_icu"] = (icu["next_intime"] - icu["outtime"]).dt.total_seconds() / (24 * 3600)

    icu["label"] = (
        icu["days_to_next_icu"].notna()
        & (icu["days_to_next_icu"] >= 0)
        & (icu["days_to_next_icu"] <= 30)
    ).astype(int)

    out = icu.groupby("hadm_id", as_index=False)["label"].max().dropna().copy()
    out["hadm_id"] = out["hadm_id"].astype(int)
    return out

# --------------------------------------------------
# Dataset
# --------------------------------------------------
class MIMICEntityDataset(Dataset):
    def __init__(self, processed_dir, label_df):
        self.processed_dir = Path(processed_dir)
        self.label_map = dict(zip(label_df["hadm_id"].astype(str), label_df["label"].astype(float)))
        self.items = []

        for p in sorted(self.processed_dir.iterdir()):
            if not p.is_dir():
                continue
            rid = p.name
            if rid not in self.label_map:
                continue

            ts_file = p / "time_series.csv"
            text_emb_candidates = list(p.glob("text_embeddings*.pt"))

            if not ts_file.exists():
                continue
            if len(text_emb_candidates) == 0:
                continue

            self.items.append({
                "record_id": rid,
                "ts_file": ts_file,
                "text_emb_file": text_emb_candidates[0],
                "label": float(self.label_map[rid]),
            })

        print(f"Dataset size: {len(self.items)}")

    def __len__(self):
        return len(self.items)

    def __getitem__(self, idx):
        row = self.items[idx]

        df = pd.read_csv(row["ts_file"])
        # keep numeric columns only, excluding obvious IDs/time columns
        drop_cols = {"record_id", "hadm_id", "subject_id", "date_time", "time_stamp"}
        feat_cols = [c for c in df.columns if c not in drop_cols]
        X = df[feat_cols].apply(pd.to_numeric, errors="coerce").fillna(0.0).to_numpy(dtype=np.float32)

        # aggregate time series to fixed vector: mean, std, min, max over time
        x_mean = np.nanmean(X, axis=0)
        x_std = np.nanstd(X, axis=0)
        x_min = np.nanmin(X, axis=0)
        x_max = np.nanmax(X, axis=0)
        x_ts = np.concatenate([x_mean, x_std, x_min, x_max], axis=0).astype(np.float32)

        text_emb = torch.load(row["text_emb_file"], map_location="cpu")
        if isinstance(text_emb, dict):
            # try common keys
            for k in ["embedding", "embeddings", "text_embedding", "hidden_states"]:
                if k in text_emb:
                    text_emb = text_emb[k]
                    break
        if isinstance(text_emb, list):
            text_emb = np.array(text_emb, dtype=np.float32)
        if torch.is_tensor(text_emb):
            text_emb = text_emb.detach().cpu().float().numpy()

        text_emb = np.asarray(text_emb, dtype=np.float32)
        if text_emb.ndim == 1:
            x_text = text_emb
        else:
            x_text = np.mean(text_emb, axis=0)

        y = np.float32(row["label"])

        return (
            torch.tensor(x_ts, dtype=torch.float32),
            torch.tensor(x_text, dtype=torch.float32),
            torch.tensor([y], dtype=torch.float32),
        )

def collate_fn(batch):
    xs, xt, y = zip(*batch)
    xs = torch.stack(xs, dim=0)
    xt = torch.stack(xt, dim=0)
    y = torch.stack(y, dim=0)
    return xs, xt, y

# --------------------------------------------------
# Old-gate multimodal classifier
# --------------------------------------------------
class OldGateClassifier(nn.Module):
    def __init__(self, ts_dim, text_dim, hidden_dim=128, dropout=0.2):
        super().__init__()

        self.ts_proj = nn.Sequential(
            nn.Linear(ts_dim, hidden_dim),
            nn.ReLU(),
            nn.Dropout(dropout),
        )

        self.text_proj = nn.Sequential(
            nn.Linear(text_dim, hidden_dim),
            nn.ReLU(),
            nn.Dropout(dropout),
        )

        # old additive gate style
        self.gate = nn.Sequential(
            nn.Linear(hidden_dim * 2, hidden_dim),
            nn.Tanh(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.Sigmoid(),
        )

        self.classifier = nn.Sequential(
            nn.Linear(hidden_dim, hidden_dim),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_dim, 1),
        )

    def forward(self, x_ts, x_text):
        h_ts = self.ts_proj(x_ts)
        h_text = self.text_proj(x_text)

        g = self.gate(torch.cat([h_ts, h_text], dim=-1))
        h = g * h_ts + (1.0 - g) * h_text
        logits = self.classifier(h)
        return logits

# --------------------------------------------------
# Train / eval
# --------------------------------------------------
def evaluate(model, loader, device):
    model.eval()
    ys, ps = [], []

    with torch.no_grad():
        for x_ts, x_text, y in loader:
            x_ts = x_ts.to(device)
            x_text = x_text.to(device)
            y = y.to(device)

            logits = model(x_ts, x_text)
            prob = torch.sigmoid(logits)

            ys.extend(y.squeeze(-1).cpu().numpy().tolist())
            ps.extend(prob.squeeze(-1).cpu().numpy().tolist())

    ys = np.array(ys)
    ps = np.array(ps)
    pred = (ps >= 0.5).astype(int)

    return {
        "auc": safe_auc(ys, ps),
        "auprc": safe_auprc(ys, ps),
        "acc": accuracy_score(ys, pred),
        "f1": f1_score(ys, pred, zero_division=0),
        "n": len(ys),
        "pos_rate": float(np.mean(ys)),
    }

def train_model(model, train_loader, val_loader, test_loader, device, lr=1e-3, epochs=20):
    criterion = nn.BCEWithLogitsLoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)

    best_val_auc = -np.inf
    best_state = None

    for epoch in range(1, epochs + 1):
        model.train()
        total_loss = 0.0

        for x_ts, x_text, y in train_loader:
            x_ts = x_ts.to(device)
            x_text = x_text.to(device)
            y = y.to(device)

            optimizer.zero_grad()
            logits = model(x_ts, x_text)
            loss = criterion(logits, y)
            loss.backward()
            optimizer.step()
            total_loss += loss.item()

        val_metrics = evaluate(model, val_loader, device)
        val_auc = val_metrics["auc"]
        val_auc_for_select = -1e9 if np.isnan(val_auc) else val_auc

        if val_auc_for_select > best_val_auc:
            best_val_auc = val_auc_for_select
            best_state = {k: v.cpu().clone() for k, v in model.state_dict().items()}

        print(
            f"Epoch {epoch:02d} | "
            f"train_loss={total_loss/ max(1,len(train_loader)):.4f} | "
            f"val_auc={val_metrics['auc']:.4f} | "
            f"val_auprc={val_metrics['auprc']:.4f} | "
            f"val_acc={val_metrics['acc']:.4f} | "
            f"val_f1={val_metrics['f1']:.4f}"
        )

    if best_state is not None:
        model.load_state_dict(best_state)

    test_metrics = evaluate(model, test_loader, device)
    return model, test_metrics

# --------------------------------------------------
# Main
# --------------------------------------------------
def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--task", type=str, required=True, choices=["mortality", "icu_readmit"])
    parser.add_argument("--mimic_root", type=str, required=True)
    parser.add_argument("--batch_size", type=int, default=16)
    parser.add_argument("--epochs", type=int, default=20)
    parser.add_argument("--seed", type=int, default=1)
    args = parser.parse_args()

    set_seed(args.seed)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print("Device:", device)

    if args.task == "mortality":
        label_df = build_mortality_labels(args.mimic_root)
    else:
        label_df = build_icu_readmit_labels(args.mimic_root)

    LABEL_DIR.mkdir(parents=True, exist_ok=True)
    out_label_path = LABEL_DIR / f"{args.task}_labels_from_runner.csv"
    label_df.to_csv(out_label_path, index=False)
    print("Saved labels to:", out_label_path)
    print(label_df["label"].value_counts(dropna=False))

    ds = MIMICEntityDataset(PROCESSED_DIR, label_df)

    n = len(ds)
    n_train = int(0.7 * n)
    n_val = int(0.15 * n)
    n_test = n - n_train - n_val

    train_ds, val_ds, test_ds = torch.utils.data.random_split(
        ds, [n_train, n_val, n_test],
        generator=torch.Generator().manual_seed(args.seed)
    )

    train_loader = DataLoader(train_ds, batch_size=args.batch_size, shuffle=True, collate_fn=collate_fn)
    val_loader = DataLoader(val_ds, batch_size=args.batch_size, shuffle=False, collate_fn=collate_fn)
    test_loader = DataLoader(test_ds, batch_size=args.batch_size, shuffle=False, collate_fn=collate_fn)

    sample_ts, sample_text, _ = ds[0]
    model = OldGateClassifier(
        ts_dim=sample_ts.shape[0],
        text_dim=sample_text.shape[0],
        hidden_dim=128,
        dropout=0.2,
    ).to(device)

    model, test_metrics = train_model(
        model, train_loader, val_loader, test_loader, device,
        lr=1e-3, epochs=args.epochs
    )

    print("\nFinal test metrics")
    for k, v in test_metrics.items():
        print(f"{k}: {v}")

    save_dir = REPO_ROOT / "run_logs"
    save_dir.mkdir(parents=True, exist_ok=True)
    torch.save(model.state_dict(), save_dir / f"oldgate_{args.task}_classifier.pt")
    print("Saved model to:", save_dir / f"oldgate_{args.task}_classifier.pt")

if __name__ == "__main__":
    main()
